services:
  subot:
    build:
      context: .
    restart: unless-stopped
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./config.json:/config/config.json:ro,Z
      - subot-data:/data

volumes:
  subot-data:
